# Import dependencies
from streamlit_components.plot_functions import PlotlyPlotter
from functions.data_functions import create_repo_workflow_map
from shared import BlobClient
import streamlit as st
import pandas as pd

def render_workflows_analysis() -> None:
    """
    Render the Streamlit dashboard for analyzing GitHub Actions workflow performance.

    Displays interactive controls to select a repository and workflow, visualize
    recent workflow run durations and status distributions, and inspect detailed
    run information in a data table. Uses JSON data generated by the workflow
    scraper to populate charts and tables.
    """
    # Render title
    st.title("Workflow Analysis")

    # Collect repo workflow map
    repo_wf_map = create_repo_workflow_map()

    # Define columns
    columns = st.columns([1, 1, 1, 2, 1])

    # Render repo select box in first column
    with columns[0]:
        repo = st.selectbox(label="Repository", options=repo_wf_map.keys())

    # Render workflow select box in second column
    with columns[1]:
        workflow = st.selectbox(label="Workflow", options=repo_wf_map[repo])

    # Read data from storage
    data = BlobClient(source="frontend") \
        .read_blob_to_dict(container="project-monitoring", input_filename=f"workflows/{repo}_{workflow}.json")

    # Generate dataframe from data
    df = pd.DataFrame(data=data)

    # Modify dataframe data
    df['created_at'] = pd.to_datetime(df['created_at'])
    df['conclusion'] = df['conclusion'].str.capitalize()
    df['status'] = df['status'].str.capitalize()

    # Render navigation button in first column
    with columns[0]:
        st.link_button(label="Navigate to Workflow",
                       url='/'.join(data[0]["html_url"].split('/')[:-2]),
                       use_container_width=True)

    # Render number of workflows slider in final column
    with columns[-1]:
        n_runs = st.slider(label="Most Recent Pipeline Runs", min_value=5, max_value=30, value=10)

    # Render expander object
    with st.expander(label="Workflow Performance Metrics", expanded=True):

        # Render column object
        columns = st.columns([2, 1])

        # Render line chart in first column
        with columns[0]:
            st.plotly_chart(PlotlyPlotter(
                df=df.head(n_runs),
                x='created_at',
                y='duration_seconds',
                title='Workflow Run Duration Over Time',
                markers=True,
                labels={'duration_seconds': 'Duration (s)', 'created_at': 'Run Date'}).plot_line())

        # Render pie chart in final column
        with columns[-1]:
            st.plotly_chart(PlotlyPlotter(
                df=df.head(n_runs),
                names='conclusion',
                title='Workflow Status Distribution'
            ).plot_pie())

    # Render dataframe in second expander
    with st.expander(label="Workflow Breakdown", expanded=True):
        st.dataframe(
            df.head(n_runs).drop(["run_number"], axis=1),
            column_config={
                "repo": st.column_config.LinkColumn(
                    "Repo",
                    help="Click to view repository",
                    display_text=r"https://github.com/powellrhys/(.*)"
                ),
                "created_at": st.column_config.DatetimeColumn(
                    "Start Datetime",
                    help="Time the workflow run started",
                    format="YYYY-MM-DD HH:mm:ss",
                ),
                "updated_at": st.column_config.DatetimeColumn(
                    "Completion Datetime",
                    help="Time the workflow run last updated",
                    format="YYYY-MM-DD HH:mm:ss",
                ),
                "workflow_name": st.column_config.TextColumn("Workflow Name"),
                "status": st.column_config.TextColumn("Status"),
                "conclusion": st.column_config.TextColumn("Conclusion"),
                "html_url": st.column_config.LinkColumn(
                    "Workflow Run",
                    help="Open the GitHub Actions run",
                    display_text="View Workflow Run"
                ),
                "duration_seconds": st.column_config.TextColumn("Duration (s)"),
            },
            hide_index=True,
        )
